Repository zalando-incubator/stackset-controller, pull requests merged in 2024-04, with the labels that each got.

#619 Ensure annotations map is not nil.
  controller/stackset.go
Labels: bugfix

#587 Support PlatformCredentialsSet versioning
  cmd/e2e/README.md
  cmd/e2e/basic_test.go
  cmd/e2e/configuration_resources_test.go
  cmd/e2e/test_environment.go
  cmd/e2e/test_utils.go
  cmd/stackset-controller/main.go
  controller/stack_resources.go
  controller/stack_resources_test.go
  controller/stackset.go
  controller/test_helpers.go
  docs/stack_crd.yaml
  docs/stackset_crd.yaml
  e2e/apply/deployment.yaml
  e2e/apply/rbac.yaml
  e2e/apply/sample.yaml
  e2e/run_e2e.sh
  pkg/apis/zalando.org/v1/zz_generated.deepcopy.go
  pkg/core/stack_resources.go
  pkg/core/stack_resources_test.go
  pkg/core/types.go
Labels: do-not-merge

#626 Update production image base image
  delivery.yaml
  go.mod
  go.sum
Labels: dependencies

#629 Update controller tools to v0.14.0
  docs/stack_crd.yaml
  docs/stackset_crd.yaml
  go.mod
  go.sum
  pkg/apis/zalando.org/v1/zz_generated.deepcopy.go
  pkg/client/informers/externalversions/factory.go
Labels: dependencies
